[phases.setup]
nixPkgs = [
    "chromium",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "cups",
    "libdrm",
    "at-spi2-core",
    "expat",
    "libX11",
    "libXcomposite",
    "libXdamage",
    "libXext",
    "libXfixes",
    "libXrandr",
    "libgbm",
    "libxcb",
    "libxkbcommon",
    "pango",
    "cairo",
    "alsa-lib",
    "dbus",
    "glib",
    "gtk3",
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python bot.py"
